version: '3'

services:
  postgres:
    image: postgres:16.2
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.95.0
    ports:
      - "4317:4317"
